# Numpy_Assignment_2::


## Name   : Akasha Mahfoozurrehman
## RollNo : PIAIC64041
## Batch   : 4 (Faisalabad)

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [9]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype=int).reshape(2,5)

In [11]:
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [12]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones(10,dtype=int).reshape(2,5)

In [13]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
flat = np.array([[0,1,2,3,4],[5,6,7,8,9]])
flat

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
flat.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [24]:
arr = np.arange(15).reshape(1,3,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [26]:
arr  = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [27]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
arr.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [31]:
arr = np.random.randint(30,size=(5,6))
arr

array([[17,  9, 15, 10, 15, 16],
       [17, 12, 12,  9, 25,  5],
       [23, 19,  6,  0, 26, 13],
       [ 6,  0, 27,  8, 28,  8],
       [ 9, 24, 19,  8, 26, 26]])

In [32]:
arr.mean()

14.6

## Question:9

### Find the standard deviation of the previous array in Q8?

In [34]:
np.random.seed(0)
arr = np.random.randint(30,size=(5,6))
print(arr)
np.std(arr)

[[12 15 21  0  3 27]
 [ 3  7  9 19 21 18]
 [ 4 23  6 24 24 12]
 [26  1  6  7 23 14]
 [24 17  5 25 13  8]]


8.423578020453462

## Question:10

### Find the median of the previous array in Q8?

In [35]:
np.random.seed(0)
arr = np.random.randint(30,size=(5,6))
print(arr)
np.median(arr)

[[12 15 21  0  3 27]
 [ 3  7  9 19 21 18]
 [ 4 23  6 24 24 12]
 [26  1  6  7 23 14]
 [24 17  5 25 13  8]]


13.5

## Question:11

### Find the transpose of the previous array in Q8?

In [38]:
np.random.seed(0)
arr = np.random.randint(30,size=(5,6))
print(arr)
arr.transpose()

[[12 15 21  0  3 27]
 [ 3  7  9 19 21 18]
 [ 4 23  6 24 24 12]
 [26  1  6  7 23 14]
 [24 17  5 25 13  8]]


array([[12,  3,  4, 26, 24],
       [15,  7, 23,  1, 17],
       [21,  9,  6,  6,  5],
       [ 0, 19, 24,  7, 25],
       [ 3, 21, 24, 23, 13],
       [27, 18, 12, 14,  8]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [39]:
arr =  np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.diagonal(arr)

array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [41]:
arr =  np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [45]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
print("Find the percentile  5th")
np.percentile(a,5)

Find the percentile  5th


1.4500000000000002

In [48]:
print("Find the percentile  95th")

np.percentile(a,95)

Find the percentile  95th


9.549999999999999

## Question:15

### How to find if a given array has any null values?

In [5]:
null = np.arange(1, 16).reshape(3, 5)
null = np.where(null % 2 != 0, np.NaN, null)
print(null)

[[nan  2. nan  4. nan]
 [ 6. nan  8. nan 10.]
 [nan 12. nan 14. nan]]


In [6]:
np.isnan(null)

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])